spring:
 datasource:
  username: root
  password: root
  url: jdbc:mysql://192.168.31.120:3306/dongbao?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  driver-class-name: com.mysql.cj.jdbc.Driver